version : "3"
services :
    frontend :
        image : forfood-frontend
        build :
            ./myvite
        ports :
            - "5173:5173"
        depends_on:
            - "backend"    
    backend :
        image : forfood-backend
        build :
            ./Backend
        ports :
            - "4300:4300"
                            
networks :
    forFood :
        driver : bridge

